### ISSUE TITLE
Utilize SMT store in cosmos-sdk app

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/cosmos-sdk#111]
For Cevmos' Block Fraud Proofs we need to have a [SMT](https://github.com/celestiaorg/smt) based store. We want to try and backport the [one from v0.46.x](https://github.com/vulcanize/cosmos-sdk/releases/tag/v0.46.0-smt-0.0.5-alpha). 

The target branch will be https://github.com/celestiaorg/cosmos-sdk/tree/manav/backport_smt

Utilize SMT in baseapp - follow up to #231

**Comment by Manav-Aggarwal** [comment]
Not needed since cosmos-sdk v0.46 supports tendermint v0.34 now. This [PR](https://github.com/cosmos/cosmos-sdk/pull/10174) should cover the contents of this issue once merged.
