### ISSUE TITLE
Add checks/tests to the newly added orchestrator/Ethereum addresses to the staking module

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/cosmos-sdk#114]
Currently, following the development under the https://github.com/celestiaorg/cosmos-sdk/pull/112 branch, we are adding two fields to the Validator struct for the staking module: `EthereumAddress` and `OrchestratorAddress`.
We will need to update the functionality and also add tests to support the new changes, check for the conditions defined below and also create new tests suits that would check for the following:

#### When creating a new validator
- The provided Orchestrator address is valid and not a duplicate (no previous validator uses the same orchestrator address)
- The provided Ethereum address is valid and not a duplicate (no previous validator uses the same Ethereum address)
- The provided Ethereum address is not the zero address

#### When editing a validator
- Same as the previous

**Comment by adlerjohn** [comment]
Once your branch is deleted after the PR is merged, that link will be dangling. Can you link to the PR proper?

**Comment by SweeXordious** [comment]
Sure

**Comment by SweeXordious** [comment]
Also, investigate if we need a separate orchestrator address field in a validator struct or the validator address is enough.
