### ISSUE TITLE
Astria: Validate fraud proofs in light clients

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/cosmos-sdk#123]
This is a parent tracking issue for validating fraud proofs with light clients using the cosmos-sdk.

At a high level we need to be able to populate a state store from a state witness and execute a single state transition, one of `BeginBlock`, `DeliverTx`, or `EndBlock` and receive an Intermediate State Root (ISR). The key difficulty is that light clients do not generally have a state store. 

Refrences:
- https://docs.tendermint.com/master/spec/p2p/messages/state-sync.html
- https://github.com/cosmos/cosmos-sdk/issues/10194

Child Issues:
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/131
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/132

**Comment by Manav-Aggarwal** [comment]
Depends on:
- celestiaorg/optimint#389

**Comment by Manav-Aggarwal** [comment]
Handled now by https://github.com/celestiaorg/rollmint/issues/514
