### ISSUE TITLE
Cevmos: Generate ISRs for all state transitions

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/cosmos-sdk#127]
To enable fraud proofs we need to modify the cosmos-sdk so an intermediate state root is generated for all state transitions. This includes `BeginBlock`, `DeliverTx`, and `EndBlock`.

**Comment by Manav-Aggarwal** [comment]
Handled in rollmint instead and closed by https://github.com/celestiaorg/rollmint/pull/567
