### ISSUE TITLE
Initialize State Store using Fraud Proof

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/cosmos-sdk#131]
To be able to verify a Fraud Proof using a light client we need to be able to start a fresh Cosmos-SDK instance with a state store that is initialized from a Fraud Proof. 

[State Sync](https://github.com/cosmos/cosmos-sdk/issues/10194) may be a good place to start

**Comment by Manav-Aggarwal** [comment]
Looking at https://github.com/cosmos/cosmos-sdk/blob/v0.46.0-rc1/store/v2alpha1/multi/snapshot.go to understand SMT store logic

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/celestiaorg/rollmint/issues/571

**Comment by Manav-Aggarwal** [comment]
Duplicate of https://github.com/celestiaorg/rollmint/issues/571
