### ISSUE TITLE
Execute single state transition given by Fraud Proof

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/cosmos-sdk#132]
We need to be able to execute a single state transition specified by a Fraud Proof.

One of 
- `BeginBlock`
- `DeliverTx`
- `EndBlock`

The ISR generated as a result of this state transition should be compared with the ISR given in a Block Header by the leader.

**Comment by Manav-Aggarwal** [comment]
Closed by: https://github.com/celestiaorg/cosmos-sdk-rollmint/pull/1
