### ISSUE TITLE
Decide on a naming convention for the Ethereum/Orchestrator address in the validator struct 

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/cosmos-sdk#136]
Currently, the Ethereum address in the validator  struct is called `EthAddress` and the orchestrator address is called `Orchestrator`. We should decide on a specific name for these which stays consistent with the qgb module on celestia-app side: https://github.com/celestiaorg/celestia-app/issues/303

**Comment by evan-forbes** [comment]
per sync discussion, this issue can be closed due to moving to v2
