### ISSUE TITLE
Allow to use Optimint instead of Tendermint

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/cosmos-sdk#17]
For Optimistic RollUps client, we need to replace ABCI-client, from default Tendermint to [Optimint](https://github.com/lazyledger/optimint).

**Comment by liamsi** [comment]
moved to https://github.com/orgs/celestiaorg/projects/10 and Triaged to post-mainnet.

**Comment by tzdybal** [comment]
This issue already implemented.
