### ISSUE TITLE
Get rid of dependabot for this fork

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/cosmos-sdk#219]
We only want to upgrade if upstream did as well, so dependabot loses most of its usefulness and it ends up pinging all of us with relentless abandon. We should consider removing it entirely from this fork.

**Comment by rootulp** [comment]
I think this issue is close-able after https://github.com/celestiaorg/cosmos-sdk/pull/233 b/c dependabot in this repo is configured to only open PRs for Celestia deps
