### ISSUE TITLE
Find a better name for this repository

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/cosmos-sdk#3]
Very low priority but we might end up having to maintain a fork of the SDK. In that case, we should change the name of this repository (s.t. people do not mistake it for a lazyledger SDK). 

Note that the name of the lazyledger-app / the binary that runs the lazyledger node can be named independently of the name of this repository.

**Comment by rootulp** [comment]
> (s.t. people do not mistake it for a lazyledger SDK)

This no longer seems like an issue given the current name of the repo is cosmos-sdk
