### ISSUE TITLE
Investigate upgrading to cosmos-sdk v0.47.x

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/cosmos-sdk#354]
## Context

https://github.com/celestiaorg/cosmos-sdk/tree/release/v0.46.x-celestia is based on the upstream cosmos-sdk v0.46.x release branch. Upstream cosmos-sdk has a newer release line that we may consider upgrading to https://github.com/cosmos/cosmos-sdk/releases/tag/v0.47.5

## Proposal

Investigate what needs to be done to create a release of this repo based on Cosmos SDK v0.47.5

**Comment by evan-forbes** [comment]
My understanding of this is that we will need to wait until there is a new version of the sdk with properly versioned modules and a Baseapp that can swap between them. This is mainly due to our requirement of single binary syncs.

**Comment by evan-forbes** [comment]
can we then close this issue @rootulp ?
