### ISSUE TITLE
Add branch protection rules for `main`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/cosmos-sdk#355]
## Context

The `main` branch was created and made the default recently. See [Slack](https://celestia-team.slack.com/archives/C02PFFCGMNW/p1697027022883829)

## Problem

`main` doesn't have any branch protection rules

## Proposal

A maintainer with permission should add branch protection rules similar to what we have on the `v0.46.x-celestia` branch

**Comment by MSevey** [comment]
looks like this was handled already.

**Comment by rootulp** [comment]
I don't think it was b/c there isn't a shield next to main

<img width="682" alt="Screenshot 2023-11-06 at 6 55 35 PM" src="https://github.com/celestiaorg/cosmos-sdk/assets/3699047/25ce629e-12ef-4e0a-b19d-4c613b9a7d17">

**Comment by rootulp** [comment]
<img width="474" alt="Screenshot 2023-11-07 at 3 05 58 PM" src="https://github.com/celestiaorg/cosmos-sdk/assets/3699047/bb4726d0-78e9-432c-84de-42d30de84e9c">

done by @MSevey
