### ISSUE TITLE
Update Prometheus Client

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/cosmos-sdk#400]
celestia-node uses a newer prometheus client that is not compatible with the one here, we should bump the one here.

**Comment by evan-forbes** [comment]
this still needs investigation into what is needed to close this issue

**Comment by rootulp** [comment]
@Wondertan which libraries do you want bumped and to which version? Perhaps:

https://github.com/celestiaorg/cosmos-sdk/blob/46df62995fe29ada7ffe0e6795bb36dcc7a09914/go.mod#L42

**Comment by rootulp** [comment]
Update from Slack: celestia-node needs to update `github.com/prometheus/common` which may also involve bumping `github.com/prometheus/client_golang`. Exact versions for these deps weren't provided so I'm assuming celestia-node wants latest for both.

Created https://github.com/prometheus/common/issues/635 while trying to bump.
