### ISSUE TITLE
Keep track of and return intermediate state roots to be included in the block

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/cosmos-sdk#8]
LazyLedger includes intermediate state roots in the block (using a reserved namespace). The preprocess step (as in tendermint/spec#5) can be used to feed those back into lazyledger-core for inclusion in the block.

Keep in mind that tendermint executes the block's Tx after the block is committed: tendermint/tendermint#7898

See also: https://github.com/lazyledger/lazyledger-core/issues/84

Also note, it could make sense to implement this after tendermint/spec#6. 
That said, ideally, the mechanism was _independent_ from from the underlying tree though. Hence, a first version could also just work with the existing IAVL tree. 

Also, if possible, we would rather implement this in the lazyledger app / module instead.

**Comment by liamsi** [comment]
Reprioritized to post-mainnet. Will use microblocks for the evmos settlement hub (which is the prio).

**Comment by tzdybal** [comment]
This issue is out of date. Fraud proofs progress is tracked in https://github.com/celestiaorg/rollmint/issues/514
