### ISSUE TITLE
Add possibility to generate state fraud proofs

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/cosmos-sdk#9]
Full nodes should be able to: 
 - generate fraud proofs and 
 - gossip those to other nodes (we still need to decide if gossiping should be done by the app or in lazyledger-core)

Additionally, there needs to be a simple API to verify fraud proofs. If possible, it would be good if we implemented this in lazyledger-app instead. But I doubt that this will work and we'll likely have to implement most of this feature directly in the SDK (as keeping track of the intermediate state roots might require changes in the SDK). The fraud proof validation logic will be in the app to some extend.

Depends on #8 (and also on #7 if we don't want different kinds of state fraud poofs).

**Comment by tzdybal** [comment]
This issue is outdated. Fraud proofs are tracked in https://github.com/celestiaorg/rollmint/issues/514.
